// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgFt5IuzrMfxiOeoDOfIsUM3ZqbAndGvQ',
    appId: '1:1041852863937:web:4a2a00c619ea4923798b40',
    messagingSenderId: '1041852863937',
    projectId: 'playmate-dbeed',
    authDomain: 'playmate-dbeed.firebaseapp.com',
    storageBucket: 'playmate-dbeed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQdAyJu-T5rSGjcYO0OFo2OxuGlKxKHE',
    appId: '1:1041852863937:android:39c19dd5718a791f798b40',
    messagingSenderId: '1041852863937',
    projectId: 'playmate-dbeed',
    storageBucket: 'playmate-dbeed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UW-vESG1TkK_I39jeEVEcArCszPwRQU',
    appId: '1:1041852863937:ios:b4b4e391a2550dbc798b40',
    messagingSenderId: '1041852863937',
    projectId: 'playmate-dbeed',
    storageBucket: 'playmate-dbeed.firebasestorage.app',
    iosBundleId: 'com.example.playmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6UW-vESG1TkK_I39jeEVEcArCszPwRQU',
    appId: '1:1041852863937:ios:b4b4e391a2550dbc798b40',
    messagingSenderId: '1041852863937',
    projectId: 'playmate-dbeed',
    storageBucket: 'playmate-dbeed.firebasestorage.app',
    iosBundleId: 'com.example.playmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgFt5IuzrMfxiOeoDOfIsUM3ZqbAndGvQ',
    appId: '1:1041852863937:web:9d46d467fb2fe145798b40',
    messagingSenderId: '1041852863937',
    projectId: 'playmate-dbeed',
    authDomain: 'playmate-dbeed.firebaseapp.com',
    storageBucket: 'playmate-dbeed.firebasestorage.app',
  );

}